trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: ./ci/unit_tests.sh
    displayName: 'Unit tests'
- job: MacOSX
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: ./ci/unit_tests.sh
    displayName: 'Unit tests'
