[package]
name = "compiler"
version = "0.1.0"
authors = ["Max Meldrum <mmeldrum@kth.se>"]
edition = "2018"

[dependencies]
codegen = { path = "../codegen" }
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
failure = "0.1.5"
cargo = "0.35.0"
