[package]
name = "protobuf"
version = "0.1.0"
authors = ["Max Meldrum <mmeldrum@kth.se>"]
edition = "2018"

[dependencies]
protobuf = "2.0"
kompact = { git = "https://github.com/kompics/kompact", branch = "master", features = ["protobuf"]}

[build-dependencies]
protoc-rust = "2.0"
