[package]
name = "codegen"
version = "0.1.0"
authors = ["Max Meldrum <mmeldrum@kth.se>"]
edition = "2018"

[dependencies]
core = { path = "../core" }
quote = "0.6"
proc-macro2 = "0.4"
rustfmt-nightly = "1.2.2"

[dev-dependencies]
compiletest_rs = { version = "*", features = ["tmp"] }
